routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('project-user', 'ProjectUserController');
    Route::resource('addresses', 'AddressesController');
    Route::resource('departaments', 'DepartamentsController');
    Route::resource('phones', 'PhonesController');
    Route::resource('projects', 'ProjectsController');
    Route::resource('users', 'UsersController');

    // para exemplo de uso sem Prettus
    Route::resource('texts', 'TextsController');
});

app/Models/Project.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Prettus\Repository\Contracts\Transformable;
use Prettus\Repository\Traits\TransformableTrait;

/**
 * Class Project.
 *
 * @package namespace App\Models;
 */
class Project extends BaseModel implements Transformable
{
    use TransformableTrait, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'responsible_id',
        'name',
        'description',
        'start_date',
        'end_date',
        'active'
    ];

    public function getStartDateAttribute($value)
    {
        return Carbon::parse($value)->format('d/m/Y');
}

    public function setStartDateAttribute($value)
    {
        $this->attributes['start_date'] = Carbon::createFromFormat('d/m/Y', $value)->format('Y-m-d');
    }

    public function getEndDateAttribute($value)
    {
        return Carbon::parse($value)->format('d/m/Y');
    }

    public function setEndDateAttribute($value)
    {
        $this->attributes['end_date'] = Carbon::createFromFormat('d/m/Y', $value)->format('Y-m-d');
    }

    public function responsible()
    {
        return $this->belongsTo(User::class);
    }

    public function users()
    {
        return $this->belongsToMany(User::class)->withTimestamps();
    }
}

app/Http/Controllers/ProjectsController.php
<?php

namespace App\Http\Controllers;

use App\Contracts\Repositories\ProjectRepository;
use App\Contracts\Repositories\UserRepository;
use App\Services\Projects\DestroyService;
use App\Services\Projects\StoreService;
use App\Services\Projects\UpdateService;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Http\Requests\ProjectCreateRequest;
use App\Http\Requests\ProjectUpdateRequest;

/**
 * Class ProjectsController.
 *
 * @package namespace App\Http\Controllers;
 */
class ProjectsController extends Controller
{
    /**
     * @var ProjectRepository
     */
    private $projectRepository;

    public function __construct(ProjectRepository $projectRepository)
    {
        parent::__construct();

        $this->projectRepository = $projectRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @param UserRepository $userRepository
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\JsonResponse|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function index(UserRepository $userRepository)
    {
        $relations = [
            'responsible'
        ];

        $projects = $this
            ->projectRepository
            ->withFilterStartEndDateCriteria()
            ->with($relations)
            ->all();

        $responsibles = $userRepository->all();

        if (request()->wantsJson()) {

            return response()->json([
                'data' => $projects,
            ]);
        }

        return view('projects.index', compact('projects', 'responsibles'));
    }

    /**
     * @param UserRepository $userRepository
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create(UserRepository $userRepository)
    {
        $responsibles_relations = [
            'departament'
        ];

        $responsibles = $userRepository->with($responsibles_relations)->all();

        return view('projects.create', compact('responsibles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreService $storeService
     * @param ProjectCreateRequest $request
     *
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function store(StoreService $storeService, ProjectCreateRequest $request)
    {
        try {

            $project = $storeService->run($request->all());

            $response = [
                'message' => 'Projeto criado.',
                'data'    => $project->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()
                ->route('projects.edit', $project->id)
                ->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param UserRepository $userRepository
     * @param int $id
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function edit(UserRepository $userRepository, $id)
    {
        $projectRelations = [
            'users'
        ];

        $responsibleRelations = [
            'departament'
        ];

        $project = $this->projectRepository->with($projectRelations)->find($id);

        $responsibles = $userRepository->with($responsibleRelations)->all();
        $users = clone $responsibles;


        return view('projects.edit', compact('project', 'responsibles', 'users'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateService $updateService
     * @param ProjectUpdateRequest $request
     * @param string $id
     *
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse
     *
     */
    public function update(UpdateService $updateService, ProjectUpdateRequest $request, $id)
    {
        try {

            $project = $updateService->run($request->all(), $id);

            $response = [
                'message' => 'Projeto atualizado.',
                'data'    => $project->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param DestroyService $destroyService
     * @param int $id
     *
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function destroy(DestroyService $destroyService, $id)
    {
        $deleted = $destroyService->run($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Projeto excluído.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Projeto excluído.');
    }
}

resources/views/projects/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-md">
        <div class="card">
            <form action="{{ route('projects.store') }}" method="POST">
                @csrf

                <div class="card-header d-flex justify-content-between">
                    <h5>Adicionar Projeto</h5>
                    <a href="{{ route('projects.index') }}" class="btn btn-secondary">Voltar</a>
                </div>

                <div class="card-body">
                    @include('layouts.validations')

                    <div class="row">
                        <div class="form-group col-md-3">
                            <label for="name">Nome</label>
                            <input id="name"
                                   type="text"
                                   class="form-control @error('name') is-invalid @enderror"
                                   name="name"
                                   value="{{ old('name') }}"
                                   required
                                   autocomplete="name"
                                   autofocus>

                            @error('name')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $message !!}</strong>
                                </span>
                            @enderror
                        </div>

                        <div class="form-group col-md-3">
                            <label for="start_date">Data Início</label>
                            <input id="start_date"
                                   type="text"
                                   class="form-control datepicker @error('start_date') is-invalid @enderror"
                                   name="start_date"
                                   value="{{ old('start_date') }}"
                                   required
                                   autocomplete="start_date">

                            @error('start_date')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $message !!}</strong>
                                </span>
                            @enderror
                        </div>

                        <div class="form-group col-md-3">
                            <label for="end_date">Data Fim</label>
                            <input id="end_date"
                                   type="text"
                                   class="form-control datepicker @error('end_date') is-invalid @enderror"
                                   name="end_date"
                                   value="{{ old('end_date') }}"
                                   required
                                   autocomplete="end_date">

                            @error('end_date')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{!! $message !!}</strong>
                                </span>
                            @enderror
                        </div>

                        <div class="form-group col-md-3">
                            <label for="responsible_id">Responsável</label>
                            <select name="responsible_id"
                                    id="responsible_id"
                                    class="form-control @error('responsible_id') is-invalid @enderror"
                                    required
                                    autocomplete="responsible_id">
                                <option value=""></option>
                                @foreach($responsibles as $responsible)
                                    <option value="{{ $responsible->id }}"
                                        {{ old('responsible_id') == $responsible->id ? 'selected' : '' }}>
                                        {{ $responsible->name }} - {{ $responsible->departament->name }}
                                    </option>
                                @endforeach
                            </select>

                            @error('responsible_id')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $message !!}</strong>
                                </span>
                            @enderror
                        </div>

                        <div class="form-group col-md-12">
                            <label for="description">Descrição</label>
                            <textarea name="description"
                                      id="description"
                                      rows="4"
                                      class="form-control @error('description') is-invalid @enderror"
                                      autocomplete="description">{{ old('description') }}</textarea>

                            @error('description')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{!! $message !!}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-success">Salvar</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/projects/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-md">
        <div class="card">
            <form action="{{ route('projects.update', $project->id) }}" method="POST">
                @csrf
                @method('PUT')

                <div class="card-header d-flex justify-content-between">
                    <h5>Atualizar Projeto</h5>
                    <a href="{{ route('projects.index') }}" class="btn btn-secondary">Voltar</a>
                </div>

                <div class="card-body">
                    @include('layouts.validations')

                    <div class="row">
                        <div class="form-group col-md-3">
                            <label for="name">Nome</label>
                            <input id="name"
                                   type="text"
                                   class="form-control @error('name') is-invalid @enderror"
                                   name="name"
                                   value="{{ old('name', $project->name) }}"
                                   required
                                   autocomplete="name"
                                   autofocus>

                            @error('name')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{!! $message !!}</strong>
                                </span>
                            @enderror
                        </div>

                        <div class="form-group col-md-3">
                            <label for="start_date">Data Início</label>
                            <input id="start_date"
                                   type="text"
                                   class="form-control datepicker @error('start_date') is-invalid @enderror"
                                   name="start_date"
                                   value="{{ old('start_date', $project->start_date) }}"
                                   required
                                   autocomplete="start_date">

                            @error('start_date')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{!! $message !!}</strong>
                                </span>
                            @enderror
                        </div>

                        <div class="form-group col-md-3">
                            <label for="end_date">Data Fim</label>
                            <input id="end_date"
                                   type="text"
                                   class="form-control datepicker @error('end_date') is-invalid @enderror"
                                   name="end_date"
                                   value="{{ old('end_date', $project->end_date) }}"
                                   required
                                   autocomplete="end_date">

                            @error('end_date')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{!! $message !!}</strong>
                                </span>
                            @enderror
                        </div>

                        <div class="form-group col-md-3">
                            <label for="responsible_id">Responsável</label>
                            <select name="responsible_id"
                                    id="responsible_id"
                                    class="form-control @error('responsible_id') is-invalid @enderror"
                                    required
                                    autocomplete="responsible_id">
                                <option value=""></option>
                                @foreach($responsibles as $responsible)
                                    <option value="{{ $responsible->id }}"
                                        {{ old('responsible_id', $project->responsible_id) == $responsible->id ? 'selected' : '' }}>
                                        {{ $responsible->name }} - {{ $responsible->departament->name }}
                                    </option>
                                @endforeach
                            </select>

                            @error('responsible_id')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{!! $message !!}</strong>
                                </span>
                            @enderror
                        </div>

                        <div class="form-group col-md-12">
                            <label for="description">Descrição</label>
                            <textarea name="description"
                                      id="description"
                                      rows="4"
                                      class="form-control @error('description') is-invalid @enderror"
                                      autocomplete="description">{{ old('description', $project->description) }}</textarea>

                            @error('description')
                            <span class="invalid-feedback" role="alert">
                                    <strong>{!! $message !!}</strong>
                                </span>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="card-footer">
                    <button type="submit" class="btn btn-success">Atualizar</button>
                </div>
            </form>
        </div>

        <project-user-component
            :users="{{ $users }}"
            :participants="{{ $project->users }}"
            project_id="{{ $project->id }}"></project-user-component>
    </div>
@endsection

resources/views/projects/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-md">
    <div class="card">
        <div class="card-header d-flex justify-content-between align-items-center">
            <h5>Projetos <span class="badge badge-info">{{ count($projects) }}</span></h5>
            <a href="{{ route('projects.create') }}" class="btn btn-secondary">Adicionar Projeto</a>
        </div>

        <div class="card-body">
            <form action="{{ route('projects.index') }}" method="GET">
                <div class="row">
                    <div class="form-group col-md-3">
                        <label for="name">Nome</label>
                        <input type="text"
                               name="name"
                               id="name"
                               class="form-control"
                               autocomplete="name"
                               value="{{ request()->input('name') }}">
                    </div>

                    <div class="form-group col-md-3">
                        <label for="responsible_id">Responsável</label>
                        <select name="responsible_id"
                                id="responsible_id"
                                class="form-control select2 h-100"
                                autocomplete="responsible_id">
                            <option value=""></option>
                            @foreach($responsibles as $responsible)
                                <option value="{{ $responsible->id }}"
                                    {{ request()->input('responsible_id') == $responsible->id ? 'selected' : '' }}>
                                    {{ $responsible->name }}
                                </option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group col-md-3">
                        <label for="start_date">Data Início</label>
                        <input type="text"
                               name="start_date"
                               id="start_date"
                               class="form-control datepicker"
                               autocomplete="start_date"
                               value="{{ request()->input('start_date') }}">
                    </div>

                    <div class="form-group col-md-3">
                        <label for="end_date">Data Fim</label>
                        <input type="text"
                               name="end_date"
                               id="end_date"
                               class="form-control datepicker"
                               autocomplete="end_date"
                               value="{{ request()->input('end_date') }}">
                    </div>

                    <div class="form-group col-md-12">
                        <button type="submit" class="btn btn-outline-primary">Buscar</button>
                        <a href="{{ route('projects.index') }}" class="btn btn-outline-secondary">Limpar</a>
                    </div>
                </div>
            </form>

            <table class="datatables table table-striped border-light mt-3">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Responsável</th>
                    <th>Data Início</th>
                    <th>Data Fim</th>
                    <th class="text-center">Ações</th>
                </tr>
                </thead>

                <tbody>
                @foreach($projects as $project)
                    <tr>
                        <td>{{ $project->id }}</td>
                        <td>{{ $project->name }}</td>
                        <td>{{ $project->responsible->name }}</td>
                        <td>{{ $project->start_date }}</td>
                        <td>{{ $project->end_date }}</td>
                        <td class="d-flex justify-content-center">
                            <a href="{{ route('projects.edit', $project->id) }}" class="mr-2 btn btn-sm btn-outline-primary">
                                <i class="far fa-edit"></i>
                            </a>

                            <form action="{{ route('projects.destroy', $project->id) }}" method="POST">
                                @method('DELETE')
                                @csrf

                                <button class="btn btn-outline-danger btn-sm">
                                    <i class="far fa-trash-alt"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection