routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
    Route::resource('project-user', 'ProjectUserController');
    Route::resource('addresses', 'AddressesController');
    Route::resource('departaments', 'DepartamentsController');
    Route::resource('phones', 'PhonesController');
    Route::resource('projects', 'ProjectsController');
    Route::resource('users', 'UsersController');

    // para exemplo de uso sem Prettus
    Route::resource('texts', 'TextsController');
});

app/Http/Controllers/AddressesController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\AddressCreateRequest;
use App\Http\Requests\AddressUpdateRequest;
use App\Services\Addresses\CreateUserService;
use App\Services\Addresses\DestroyService;
use App\Services\Addresses\UpdateService;
use Prettus\Validator\Exceptions\ValidatorException;
use App\Contracts\Repositories\AddressRepository;

/**
 * Class AddressesController.
 *
 * @package namespace App\Http\Controllers;
 */
class AddressesController extends Controller
{
    /**
     * @var AddressRepository
     */
    private $addressRepository;

    /**
     * AddressablesController constructor.
     * @param AddressRepository $addressRepository
     */
    public function __construct(AddressRepository $addressRepository)
    {
        parent::__construct();

        $this->addressRepository = $addressRepository;
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateUserService $createUserService
     * @param AddressCreateRequest $request
     *
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse
     *
     */
    public function store(CreateUserService $createUserService, AddressCreateRequest $request)
    {
        try {

            $address = $createUserService->run($request->all());

            $response = [
                'message' => 'Endereço criado.',
                'data'    => $address->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {
            if ($request->wantsJson()) {
                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $address = $this->addressRepository->find($id);

        return view('addresses.edit', compact('address'));
    }

    /**
     * @param UpdateService $updateService
     * @param AddressUpdateRequest $request
     * @param $id
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse
     */
    public function update(UpdateService $updateService, AddressUpdateRequest $request, $id)
    {
        try {

            $address = $updateService->run($request->all(), $id);

            $response = [
                'message' => 'Endereço atualizado.',
                'data'    => $address->toArray(),
            ];

            if ($request->wantsJson()) {

                return response()->json($response);
            }

            return redirect()->back()->with('message', $response['message']);
        } catch (ValidatorException $e) {

            if ($request->wantsJson()) {

                return response()->json([
                    'error'   => true,
                    'message' => $e->getMessageBag()
                ]);
            }

            return redirect()->back()->withErrors($e->getMessageBag())->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param DestroyService $destroyService
     * @param int $id
     *
     * @return \Illuminate\Http\JsonResponse|\Illuminate\Http\RedirectResponse
     */
    public function destroy(DestroyService $destroyService, $id)
    {
        $deleted = $destroyService->run($id);

        if (request()->wantsJson()) {

            return response()->json([
                'message' => 'Endereço excluído.',
                'deleted' => $deleted,
            ]);
        }

        return redirect()->back()->with('message', 'Endereço excluído.');
    }
}

resources/views/addresses/create.blade.php
<form action="{{ route('addresses.store') }}" method="POST">
    @csrf

    <input type="hidden" name="user_id" value="{{ $user->id }}">

    <div class="row">
        <div class="form-group col-md-2">
            <label for="zipcode">
                CEP &nbsp;<i style="display: none;" class="fas fa-spinner zipcode-loader fa-pulse text-secondary"></i>
            </label>
            <input type="text"
                   required
                   name="zipcode"
                   id="zipcode"
                   class="form-control zipcode-mask @error('zipcode') is-invalid @enderror">

            <small style="display: none;" class="text-danger zipcode-error font-weight-bold">Cep não encontrado</small>

            @error('zipcode')
            <span class="invalid-feedback" role="alert">
                    <strong>{!! $message ?? '' !!}</strong>
                </span>
            @enderror
        </div>

        <div class="form-group col-md-8">
            <label for="street">Logradouro</label>
            <input type="text"
                   required
                   name="street"
                   id="street"
                   class="form-control @error('street') is-invalid @enderror">

            @error('street')
            <span class="invalid-feedback" role="alert">
                    <strong>{!! $message !!}</strong>
                </span>
            @enderror
        </div>

        <div class="form-group col-md-2">
            <label for="number">Número</label>
            <input type="number"
                   required
                   name="number"
                   id="number"
                   class="form-control @error('number') is-invalid @enderror">

            @error('number')
                <span class="invalid-feedback" role="alert">
                    <strong>{!! $message !!}</strong>
                </span>
            @enderror
        </div>

        <div class="form-group col-md-5">
            <label for="district">Bairro</label>
            <input type="text"
                   required
                   name="district"
                   id="district"
                   class="form-control @error('district') is-invalid @enderror">

            @error('district')
                <span class="invalid-feedback" role="alert">
                    <strong>{!! $message !!}</strong>
                </span>
            @enderror
        </div>

        <div class="form-group col-md-5">
            <label for="city">Cidade</label>
            <input type="text"
                   required
                   name="city"
                   id="city"
                   class="form-control @error('zipcode') is-invalid @enderror">

            @error('city')
                <span class="invalid-feedback" role="alert">
                    <strong>{!! $message !!}</strong>
                </span>
            @enderror
        </div>

        <div class="form-group col-md-2">
            <label for="state">Estado</label>
            <select id="state" name="state" class="form-control @error('state') is-invalid @enderror">
                <option value="">Selecione...</option>
                <option value="AC">Acre</option>
                <option value="AL">Alagoas</option>
                <option value="AP">Amapá</option>
                <option value="AM">Amazonas</option>
                <option value="BA">Bahia</option>
                <option value="CE">Ceará</option>
                <option value="DF">Distrito Federal</option>
                <option value="ES">Espírito Santo</option>
                <option value="GO">Goiás</option>
                <option value="MA">Maranhão</option>
                <option value="MT">Mato Grosso</option>
                <option value="MS">Mato Grosso do Sul</option>
                <option value="MG">Minas Gerais</option>
                <option value="PA">Pará</option>
                <option value="PB">Paraíba</option>
                <option value="PR">Paraná</option>
                <option value="PE">Pernambuco</option>
                <option value="PI">Piauí</option>
                <option value="RJ">Rio de Janeiro</option>
                <option value="RN">Rio Grande do Norte</option>
                <option value="RS">Rio Grande do Sul</option>
                <option value="RO">Rondônia</option>
                <option value="RR">Roraima</option>
                <option value="SC">Santa Catarina</option>
                <option value="SP">São Paulo</option>
                <option value="SE">Sergipe</option>
                <option value="TO">Tocantins</option>
                <option value="EX">Estrangeiro</option>
            </select>

            @error('state')
            <span class="invalid-feedback" role="alert">
                    <strong>{!! $message !!}</strong>
                </span>
            @enderror
        </div>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Incluir</button>
    </div>
</form>

<script type="application/javascript">
    $(document).ready(function () {
        $('#zipcode').keyup(function () {
            let zipcode = $(this).val();

            if (zipcode.length === 9) {
                $(".zipcode-loader").show();

                getCep(zipcode)
                    .then((response) => {
                        $(".zipcode-loader").hide();
                        $(".zipcode-error").hide();

                        $(this).removeClass('is-invalid');

                        setAddressFields(response);
                    })
                    .catch((error) => {
                        $(".zipcode-loader").hide();
                        $(".zipcode-error").show();

                        $(this).addClass('is-invalid');

                        clearAddressFields();
                    });
            }
        });
    });

    function setAddressFields(data) {
        $("#street").val(data.logradouro || data.street);
        $("#district").val(data.bairro || data.neighborhood);
        $("#city").val(data.localidade || data.city);
        $("#state").val(data.uf || data.state);
    }

    function clearAddressFields() {
        $("#street").val(null);
        $("#district").val(null);
        $("#city").val(null);
        $("#state").val(null);
    }
</script>

resources/views/addresses/edit.blade.php
<form action="{{ route('addresses.update', $address->id) }}" method="POST">
    @method('PUT')
    @csrf

    <div class="row">
        <div class="form-group col-md-2">
            <label for="zipcode">
                CEP &nbsp;<i style="display: none;" class="fas fa-spinner zipcode-loader fa-pulse text-secondary"></i>
            </label>
            <input type="text"
                   required
                   name="zipcode"
                   id="zipcode"
                   value="{{ $address->zipcode ?? '' }}"
                   class="form-control zipcode-mask @error('zipcode') is-invalid @enderror">

            <small style="display: none;" class="text-danger zipcode-error font-weight-bold">Cep não encontrado</small>

            @error('zipcode')
            <span class="invalid-feedback" role="alert">
                    <strong>{!! $message ?? '' !!}</strong>
                </span>
            @enderror
        </div>

        <div class="form-group col-md-8">
            <label for="street">Logradouro</label>
            <input type="text"
                   required
                   name="street"
                   id="street"
                   value="{{ $address->street ?? '' }}"
                   class="form-control @error('street') is-invalid @enderror">

            @error('street')
            <span class="invalid-feedback" role="alert">
                    <strong>{!! $message !!}</strong>
                </span>
            @enderror
        </div>

        <div class="form-group col-md-2">
            <label for="number">Número</label>
            <input type="number"
                   required
                   name="number"
                   id="number"
                   value="{{ $address->number ?? '' }}"
                   class="form-control @error('number') is-invalid @enderror">

            @error('number')
            <span class="invalid-feedback" role="alert">
                    <strong>{!! $message !!}</strong>
                </span>
            @enderror
        </div>

        <div class="form-group col-md-4">
            <label for="district">Bairro</label>
            <input type="text"
                   required
                   name="district"
                   id="district"
                   value="{{ $address->district ?? '' }}"
                   class="form-control @error('district') is-invalid @enderror">

            @error('district')
            <span class="invalid-feedback" role="alert">
                    <strong>{!! $message !!}</strong>
                </span>
            @enderror
        </div>

        <div class="form-group col-md-5">
            <label for="city">Cidade</label>
            <input type="text"
                   required
                   name="city"
                   id="city"
                   value="{{ $address->city ?? '' }}"
                   class="form-control @error('zipcode') is-invalid @enderror">

            @error('city')
            <span class="invalid-feedback" role="alert">
                    <strong>{!! $message !!}</strong>
                </span>
            @enderror
        </div>

        <div class="form-group col-md-3">
            <label for="state">Estado</label>
            <select id="state" name="state" class="form-control @error('state') is-invalid @enderror">
                <option value="">Selecione...</option>
                <option value="AC" {{ $address->state == 'AC' ? 'selected' : '' }}>Acre</option>
                <option value="AL" {{ $address->state == 'AL' ? 'selected' : '' }}>Alagoas</option>
                <option value="AP" {{ $address->state == 'AP' ? 'selected' : '' }}>Amapá</option>
                <option value="AM" {{ $address->state == 'AM' ? 'selected' : '' }}>Amazonas</option>
                <option value="BA" {{ $address->state == 'BA' ? 'selected' : '' }}>Bahia</option>
                <option value="CE" {{ $address->state == 'CE' ? 'selected' : '' }}>Ceará</option>
                <option value="DF" {{ $address->state == 'DF' ? 'selected' : '' }}>Distrito Federal</option>
                <option value="ES" {{ $address->state == 'ES' ? 'selected' : '' }}>Espírito Santo</option>
                <option value="GO" {{ $address->state == 'GO' ? 'selected' : '' }}>Goiás</option>
                <option value="MA" {{ $address->state == 'MA' ? 'selected' : '' }}>Maranhão</option>
                <option value="MT" {{ $address->state == 'MT' ? 'selected' : '' }}>Mato Grosso</option>
                <option value="MS" {{ $address->state == 'MS' ? 'selected' : '' }}>Mato Grosso do Sul</option>
                <option value="MG" {{ $address->state == 'MG' ? 'selected' : '' }}>Minas Gerais</option>
                <option value="PA" {{ $address->state == 'PA' ? 'selected' : '' }}>Pará</option>
                <option value="PB" {{ $address->state == 'PB' ? 'selected' : '' }}>Paraíba</option>
                <option value="PR" {{ $address->state == 'PR' ? 'selected' : '' }}>Paraná</option>
                <option value="PE" {{ $address->state == 'PE' ? 'selected' : '' }}>Pernambuco</option>
                <option value="PI" {{ $address->state == 'PI' ? 'selected' : '' }}>Piauí</option>
                <option value="RJ" {{ $address->state == 'RJ' ? 'selected' : '' }}>Rio de Janeiro</option>
                <option value="RN" {{ $address->state == 'RN' ? 'selected' : '' }}>Rio Grande do Norte</option>
                <option value="RS" {{ $address->state == 'RS' ? 'selected' : '' }}>Rio Grande do Sul</option>
                <option value="RO" {{ $address->state == 'RO' ? 'selected' : '' }}>Rondônia</option>
                <option value="RR" {{ $address->state == 'RR' ? 'selected' : '' }}>Roraima</option>
                <option value="SC" {{ $address->state == 'SC' ? 'selected' : '' }}>Santa Catarina</option>
                <option value="SP" {{ $address->state == 'SP' ? 'selected' : '' }}>São Paulo</option>
                <option value="SE" {{ $address->state == 'SE' ? 'selected' : '' }}>Sergipe</option>
                <option value="TO" {{ $address->state == 'TO' ? 'selected' : '' }}>Tocantins</option>
                <option value="EX" {{ $address->state == 'EX' ? 'selected' : '' }}>Estrangeiro</option>
            </select>

            @error('state')
            <span class="invalid-feedback" role="alert">
                    <strong>{!! $message !!}</strong>
                </span>
            @enderror
        </div>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-success btn-block">Atualizar</button>
    </div>
</form>

resources/views/addresses/index.blade.php
<div class="card mt-5">
    <div class="card-header d-flex justify-content-between">
        <h5>Endereços</h5>
    </div>

    <div class="card-body">
        @include('addresses.create')

        <div class="mt-3">
            <table class="table table-bordered">
                <thead>
                <tr>
                    <th>CEP</th>
                    <th>Logradouro</th>
                    <th>Número</th>
                    <th>Cidade</th>
                    <th>Bairro</th>
                    <th>Estado</th>
                    <th class="text-center">Ações</th>
                </tr>
                </thead>

                <tbody>
                @forelse($model->addresses as $address)
                    <tr>
                        <td class="zipcode-mask">{{ $address->zipcode }}</td>
                        <td>{{ $address->street }}</td>
                        <td>{{ $address->number }}</td>
                        <td>{{ $address->city }}</td>
                        <td>{{ $address->district }}</td>
                        <td>{{ $address->state }}</td>
                        <td class="d-flex justify-content-center">
                            <button type="button"
                                    data-id="{{ $address->id }}"
                                    class="mr-2 btn btn-sm btn-outline-primary"
                                    data-toggle="modal" data-target="#editAddressModal">
                                <i class="far fa-edit"></i>
                            </button>

                            <form action="{{ route('addresses.destroy', $address->id) }}" method="POST">
                                @method('DELETE')
                                @csrf

                                <button class="btn btn-outline-danger btn-sm">
                                    <i class="far fa-trash-alt"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                @empty
                    <tr>
                        <td colspan="7" class="text-center font-weight-bolder">Nenhum endereço cadastrado</td>
                    </tr>
                @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>


<div class="modal fade" id="editAddressModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Editar Contato</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>

            <div class="modal-body" id="editAddressContent"></div>
        </div>
    </div>
</div>

<script type="application/javascript">
    $(document).ready(function () {
        $('#editAddressModal').on('show.bs.modal', function (e) {
            $('.preloader').show();

            let id = $(e.relatedTarget).data('id');

            axios.get('/addresses/'+id+'/edit')
                .then((response) => {
                    $('.preloader').hide();

                    $('#editAddressContent').html(response.data);
                })
                .catch(() => {
                    $('.preloader').hide();
                });
        });
    });
</script>